language: python

python:
  - "3.8"

install:
  - pip install pipenv
  - pipenv lock
  - pipenv install --ignore-pipfile --dev

script: pytest

notifications:
  email:
    - on_success: change
    - on_failure: always